### ISSUE TITLE
Support .jest.clearAllMocks()

### ISSUE THREAD

**Issue by vajahath** [nicolo-ribaudo/jest-light-runner#18]
I'm not using require/import mock.

The following snippet works with mocking
```ts
// working
class Adder {
  constructor(public getValueToAdd: () => number) {}

  add(digit: number) {
    return this.getValueToAdd() + digit;
  }
}

test("testing mock", () => {
  const mockGetValueToAddFunction = jest.fn().mockReturnValue(1);
  const adder = new Adder(mockGetValueToAddFunction);

  const result = adder.add(2);

  expect(result).toBe(3);
  expect(mockGetValueToAddFunction).toHaveBeenCalled();
});
```
However adding 
```ts
beforeEach(() => jest.clearAllMocks());
```
results in 
```
Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'length')

      at file:/home/xxxx/node_modules/jest-light-runner/src/worker-runner.js:222:29
          at Array.filter (<anonymous>)
      at toTestResult (file:/home/xxxx/node_modules/jest-light-runner/src/worker-runner.js:222:8)
      at default (file:/home/xxxx/node_modules/jest-light-runner/src/worker-runner.js:78:10)
      at async /home/xxx/node_modules/piscina/dist/src/worker.js:141:26
```

**Comment by nicolo-ribaudo** [comment]
Would you like to open a PR? It probably just needs to be added here: https://github.com/nicolo-ribaudo/jest-light-runner/blob/683a5c682105a95abf77803ad20ed19f57918d3b/src/global-setup.js#L24

(please test if it works in your project!)
