### ISSUE TITLE
Investigate `--coverage` support

### ISSUE THREAD

**Issue by nicolo-ribaudo** [nicolo-ribaudo/jest-light-runner#6]
It's possible that this is already working, because Babel uses this runner and collects a coverage when running it's tests: https://github.com/babel/babel/runs/5789483528. If it already works great, I just need to document it.

It's also possible that it's only working partially, or that it's not working at all and that Babel's coverage reporting is based on something else.

(cc @psychobolt - https://github.com/facebook/jest/issues/9430#issuecomment-1086946059)

**Comment by SimenB** [comment]
I would assume coverage doesn't work, but I've been wrong before! 😀 However, adding support for v8 based coverage should be straight forward. E.g. use https://github.com/SimenB/collect-v8-coverage (what Jest uses) and store it as `v8Coverage` on the test result: https://github.com/facebook/jest/blob/80cf80055682919251b9567ef482755d5f060d47/packages/jest-runner/src/runTest.ts#L338.

**Comment by nicolo-ribaudo** [comment]
Thank you!

**Comment by fisker** [comment]
I don't think the coverage works, I added `c8` when using in Prettier, https://github.com/prettier/prettier/blob/3cbee742a792413211eea1e4fe2d0dad26ff37ea/.github/workflows/dev-test.yml#L79

**Comment by psychobolt** [comment]
Yes I assumed ```--coverageReporter=v8``` would work. However, that seems to not work as well.

**Comment by SimenB** [comment]
Yeah, runner needs to hook it up. But should as mentioned be very little code 🤞

**Comment by fisker** [comment]
This CI log maybe useful, I got a error message [here](https://github.com/prettier/prettier/runs/5847198949?check_suite_focus=true#step:6:1140)

<details>
<summary>Details</summary>
ERROR: Cannot assign to read only property 'message' of object 'SyntaxError: import.meta may appear only with 'sourceType: "module"' (293:39)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.'
STACK: TypeError: Cannot assign to read only property 'message' of object 'SyntaxError: import.meta may appear only with 'sourceType: "module"' (293:39)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.'
    at parser (/home/runner/work/prettier/prettier/node_modules/@babel/core/lib/parser/index.js:87:21)
    at parser.next (<anonymous>)
    at parse (/home/runner/work/prettier/prettier/node_modules/@babel/core/lib/parse.js:31:37)
    at parse.next (<anonymous>)
    at evaluateSync (/home/runner/work/prettier/prettier/node_modules/gensync/index.js:251:28)
    at sync (/home/runner/work/prettier/prettier/node_modules/gensync/index.js:89:14)
    at getAst (/home/runner/work/prettier/prettier/node_modules/istanbul-lib-instrument/src/read-coverage.js:16:12)
    at readInitialCoverage (/home/runner/work/prettier/prettier/node_modules/istanbul-lib-instrument/src/read-coverage.js:31:17)
    at generateEmptyCoverage (/home/runner/work/prettier/prettier/node_modules/@jest/reporters/build/generateEmptyCoverage.js:155:72)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


</details>

**Comment by fisker** [comment]
And the error disappear when add `coverageProvider: 'v8'`, [log](https://github.com/prettier/prettier/runs/5850966240?check_suite_focus=true#step:6:1140)

**Comment by nicolo-ribaudo** [comment]
Yeah, the error is probably caused by istanbul/nyc reading coverage data that does not exist (I'm still wondering how Babel's coverage currently works :shrug:)

**Comment by fisker** [comment]
I wounder why this error swallowed? https://github.com/nicolo-ribaudo/jest-light-runner/issues/6#issuecomment-1090208879

**Comment by SimenB** [comment]
See #13, I think that's working 🙂

**Comment by ticup** [comment]
Hi all, this might be obvious for some, but maybe not for others, so I'm leaving it here.

The jest-light-runner decreased our running time by almost a 5-fold, which is a tremendous performance increase, thanks! 🎉 

But we couldn't get the coverage to work trying the proposed on-the-fly babel-register-esm loader option, but that doesn't seem to work.



As an alternative, we now use the v8 instrumentation and c8 as follows:

````
npx c8 npx jest
````
